import Head from 'next/head'
import About from '../components/About'
import Contact from '../components/Contact'
import Main from '../components/Main'

import Projects from '../components/Projects'
import Skills from '../components/Skills'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Williams Amaya | Back-End dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo_tiny.png" />
      </Head>
      
      <Main/>
      <About/>
      <Skills/>
      <Projects/>
      <Contact/>
    </div>
  )
}
